const state={course:"daily",mode:"listen",items:[],index:0,audio:null,playing:false,revealed:false,ratings:JSON.parse(localStorage.getItem("chunk-response-ratings")||"{}")};
const $=s=>document.querySelector(s),els={status:$("#asset-status"),course:document.querySelectorAll(".course-button"),mode:document.querySelectorAll(".mode-tab"),modeLabel:$("#mode-label"),progress:$("#progress"),chunk:$("#chunk-label"),ja:$("#japanese-text"),en:$("#english-text"),cue:$("#cue-text"),play:$("#play-button"),prev:$("#previous-button"),next:$("#next-button"),ratings:$("#rating-actions"),can:$("#can-button"),cannot:$("#cannot-button"),swipe:$("#swipe-hint"),queue:$("#queue-list"),queueCopy:$("#queue-copy"),settings:$("#settings-panel"),settingsButton:$("#settings-button"),repeat:$("#repeat-count"),pause:$("#pause-multiplier"),card:$("#learning-card")};
function parseCsv(t){const rows=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i+=1){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i+=1}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i+=1;row.push(cell);if(row.length>1)rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const[h,...data]=rows;return data.map(r=>Object.fromEntries(h.map((key,i)=>[key.replace(/^\uFEFF/,""),r[i]||""])))}
const pad=n=>String(n).padStart(3,"0");
async function loadDaily(){const rows=parseCsv(await fetch("./chunks_120_examples.csv").then(r=>r.text()));return rows.map(r=>({id:r.id,chunk:r["チャンク"],chunkJa:r["チャンク日本語訳"],english:r["英文"],japanese:r["例文日本語訳"],audio:`./${r["音声ファイル"]}`}))}
async function loadEdtech(){const text=await fetch("./edtech_it_chunk_examples.md").then(r=>r.text());let num=0,chunk="",chunkJa="",ex=0;const items=[];text.split("\n").forEach(line=>{const h=line.match(/^##\s+(\d+)\.\s+(.+?)\s*[—–-]\s*(.+)$/),s=line.match(/^[-*]\s*\(([EI])\)\s+(.+)$/);if(h){num=Number(h[1]);chunk=h[2].trim();chunkJa=h[3].trim();ex=0}if(s){ex+=1;items.push({id:`${pad(num)}-${String(ex).padStart(2,"0")}`,chunk,chunkJa,english:s[2].trim(),japanese:"",audio:`./edtech-it-audio/${pad(num)}-${String(ex).padStart(2,"0")}.mp3`})}});return items}
const current=()=>state.items[state.index],wait=ms=>new Promise(r=>setTimeout(r,ms));
function speak(text){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ja-JP";u.rate=.9;speechSynthesis.speak(u)}
function queue(){const item=current(),same=state.items.filter(x=>x.chunk===item.chunk);els.queue.innerHTML=same.map(x=>`<li class="${x.id===item.id?"is-current":""}">${x.english}</li>`).join("");els.queueCopy.textContent=`「${item.chunk}」の例文を ${same.length} 文続けて練習します。`}
function render(){const item=current();if(!item)return;const recall=state.mode==="recall",apply=state.mode==="apply";els.modeLabel.textContent=apply?"APPLY · PREPARING":recall?"RECALL · SPEAK":"LISTEN & REPEAT";els.progress.textContent=`${state.index+1} / ${state.items.length}`;els.chunk.textContent=item.chunk;els.ja.textContent=recall?(item.japanese||`${item.chunkJa} を使って、英文を口に出してみましょう。`):(item.japanese||item.chunkJa);els.en.textContent=apply?"英語を組み立ててください":recall&&!state.revealed?"英語を組み立ててください":item.english;els.cue.textContent=apply?"応用問題の自動生成は次の段階で追加します。今は既習例文で型を固めましょう。":recall?"日本語を聞いたら話してください。ポーズの後、正解の英文が流れます。":"再生して、聞こえた通りに続けて話してください。";els.ratings.hidden=!recall;els.swipe.hidden=!recall;els.play.disabled=apply;els.play.innerHTML=`<span aria-hidden="true">${state.playing?"■":"▶"}</span> ${recall?"問題を始める":state.playing?"停止する":"再生する"}`;queue()}
function stop(){state.audio?.pause();state.audio=null;state.playing=false;render()}function play(url){return new Promise((yes,no)=>{state.audio=new Audio(url);state.audio.onended=yes;state.audio.onerror=no;state.audio.play().catch(no)})}
async function listen(){const item=current();state.playing=true;render();try{for(let i=0;i<Number(els.repeat.value);i+=1){await play(item.audio);if(i<Number(els.repeat.value)-1)await wait(700*Number(els.pause.value))}}catch{els.status.textContent="音声を再生できません。GitHub上の音声ファイルを確認してください。"}finally{state.playing=false;state.audio=null;render()}}
async function recall(){const item=current();state.playing=true;state.revealed=false;render();speak(item.japanese||`${item.chunkJa} を使って、英文を口に出してみましょう。`);try{const probe=new Audio(item.audio);await new Promise(done=>{probe.onloadedmetadata=done;probe.onerror=done;probe.load()});await wait(Math.max(1600,(Number.isFinite(probe.duration)?probe.duration*1000:3000)*Number(els.pause.value)));state.revealed=true;render();await play(item.audio)}catch{els.status.textContent="正解音声を再生できません。"}finally{state.playing=false;state.audio=null;render()}}
function move(d){stop();state.revealed=false;state.index=(state.index+d+state.items.length)%state.items.length;render()}function rate(r){state.ratings[current().id]=r;localStorage.setItem("chunk-response-ratings",JSON.stringify(state.ratings));move(1)}
async function changeCourse(course){stop();state.course=course;els.status.textContent="教材を切り替えています…";state.items=course==="daily"?await loadDaily():await loadEdtech();state.index=0;els.course.forEach(b=>b.classList.toggle("is-selected",b.dataset.course===course));els.status.textContent=`${course==="daily"?"日常／ビジネス":"EduTech／IT"}：${state.items.length}例文・音声を読み込みました`;render()}
els.play.addEventListener("click",()=>state.playing?stop():(state.mode==="recall"?recall():listen()));els.prev.addEventListener("click",()=>move(-1));els.next.addEventListener("click",()=>move(1));els.can.addEventListener("click",()=>rate("can"));els.cannot.addEventListener("click",()=>rate("cannot"));els.course.forEach(b=>b.addEventListener("click",()=>changeCourse(b.dataset.course)));els.mode.forEach(b=>b.addEventListener("click",()=>{stop();state.revealed=false;state.mode=b.dataset.mode;els.mode.forEach(t=>{const a=t===b;t.classList.toggle("is-selected",a);t.setAttribute("aria-selected",a)});render()}));els.settingsButton.addEventListener("click",()=>{const open=els.settings.hidden;els.settings.hidden=!open;els.settingsButton.setAttribute("aria-expanded",String(open))});let x=null;els.card.addEventListener("pointerdown",e=>x=e.clientX);els.card.addEventListener("pointerup",e=>{if(state.mode!=="recall"||x===null)return;const d=e.clientX-x;if(Math.abs(d)>84)rate(d>0?"can":"cannot");x=null});changeCourse("daily");if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
